###########################
#   General configuration #
###########################

baseURL = "https://thediligentlearner.github.io/"
languageCode = "en-us"
title = "The Diligent Learner"

# Pagination for articles list layout
paginate = 20
paginatePath = "page"

# Hugo widgets
googleAnalytics = "UA-123-45" # Note: fake value. Put real value !

#enableGitInfo = true
#disableKinds = ["taxonomyTerm"]


######################################
# Groups of configuration parameters #
######################################

[related]
  threshold = 50 
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "series"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[outputs]
  section = ["HTML", "JSON", "RSS"] # JSON is used by search page

[permalinks]
  articles = "/:section/:year/:month/:filename/"
  pics-and-trips = "/:section/:filename/"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
 
[params]
  ddateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch" #???

  # Metadata
  description = "Text about my cool site" #Default used for metadata (if not defined in frontmatter)
  images = ["/assets/img/site-feature-image.jpg"] ##Default used for metadata (if not defined in frontmatter)
  title = "My cool site" #Used for metadata
  
  # Social Icons are used as inline svg, so they can be customized through CSS
  # Located at folder: partials/social-icons/
  # These are the links attached to each icon
  linkedinLink = "https://linkedin.com"
  twitterLink = "https://twitter.com"
  facebookLink = "https://facebook.com"
  instagramLink = "https://instagram.com"
  githubLink = "https://github.com"
  emailLink = "#"


# Main menus
# "pre" is the svg icon, shown in front of the menu name
[menu]

  [[menu.main]]
    name = "Home"
    pre = "icons/home-icon.svg"
    url = "/"
    weight = 1

  #[[menu.main]]
  #  name = "About"
  #  pre = "icons/person-icon.svg"
  #  url = "/about/"
  #  weight = 2  
  
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    pre = "icons/pencil-icon.svg"
    url = "/articles/"
    weight = 3

   [[menu.main]]
     parent = "articles"
     name = "Browse"
     pre = "icons/explore-icon.svg"
     url = "/articles/"
     weight = 4  

   [[menu.main]]
     parent = "articles"
     name = "Search"
     pre = "icons/magnifier2-icon.svg"
     url = "/search/"
     weight = 4.5  

   [[menu.main]]
     parent = "articles"
     name = "Series"
     pre = "icons/star-icon.svg"
     url = "/series/"
     weight = 5  

  [[menu.main]]
    name = "Projects"
    pre = "icons/project-icon.svg"
    url = "/projects/"
    weight = 6

  [[menu.main]]
    name = "Resources"
    pre = "icons/tool-icon.svg"
    url = "/resources/"
    weight = 7

  #[[menu.main]]
  #  name = "Pics & Trips"
  #  pre = "icons/camera-icon.svg"
  #  url = "/pics-and-trips/"
  #  weight = 8

  #[[menu.main]]
  #  name = "Contact"
  #  pre = "icons/project-icon.svg"
  #  url = "/contact/"
  #  weight = 9

  [[menu.main]]
    name = "About"
    pre = "icons/person-icon.svg"
    url = "/about/"
    weight = 10

# Disable cache during live server
#[caches]
#[caches.getjson]
#dir = ":cacheDir/:project"
#maxAge = 0
