baseURL = "http://example.org/"
languageCode = "en-us"
title = "RogerGallart Personal Website"
paginate = 3
paginatePath = "page"
googleAnalytics = "UA-123-45" # Put real value

#enableGitInfo = true
#disableKinds = ["taxonomyTerm"]


######################################
# Groups of configuration parameters #
######################################

#[caches]
#[caches.getjson]
#dir = ":cacheDir/:project"
#maxAge = 0

[related]
  threshold = 50 
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "series"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[outputs]
  section = ["HTML", "JSON", "RSS"]

[permalinks]
  articles = "/:section/:year/:month/:filename/"
  pics-and-trips = "/:section/:filename/"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
 
[params]
  ddateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch"
  description = "Text about my cool site" #Used for metadata if not defined in frontmatter
  images = ["/images/site-feature-image.jpg"] #Used for metadata if not defined in frontmatter
  title = "My cool site" #Used for metadata

[menu]
  [[menu.main]]
    name = "Home"
    pre = "mdi mdi-home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "mdi mdi-file-document-edit-outline"
    url = "/about/"
    weight = 2  
  
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    pre = "mdi mdi-file-document-edit-outline"
    url = "/articles/"
    weight = 3

    [[menu.main]]
      parent = "articles"
      name = "Browse"
      pre = "mdi mdi-file-document-edit-outline"
      url = "/articles/"
      weight = 4  

    [[menu.main]]
      parent = "articles"
      name = "Search"
      pre = "mdi mdi-magnify"
      url = "/search/"
      weight = 4.5  

    [[menu.main]]
      parent = "articles"
      name = "Series"
      pre = "mdi mdi-file-document-edit-outline"
      url = "/series/"
      weight = 5  

  [[menu.main]]
    name = "Projects"
    pre = "mdi mdi-lightbulb-on-outline"
    url = "/projects/"
    weight = 6

  [[menu.main]]
    name = "Resources"
    pre = "mdi mdi-book-open-page-variant"
    url = "/resources/"
    weight = 7

  [[menu.main]]
    name = "Pics and Trips"
    pre = "mdi mdi-airplane"
    url = "/pics-and-trips/"
    weight = 8

  [[menu.main]]
    name = "Contact"
    pre = "mdi mdi-email-outline"
    url = "/contact/"
    weight = 9
